### ISSUE TITLE
关于武士月连错误

### ISSUE THREAD

**Issue by Dream1995** [Yuee98/FFXIVOneButtonCombo#1]
您好，首先非常感谢您发开的一键连击。
我在使用的过程中发现武士的 月连 存在问题，在没有闪先打月连的情况下打完阵风后，技能就变成叶隐了，故无法使用，给我造成了一定的困扰。
期待您的更新与回复，非常感谢！

**Comment by Yuee98** [comment]
问题出现原正则在无闪时会错误的将默想层数识别为闪状态，当默想层数为2时判断为月闪存在，触发防打重复闪的叶隐
更新了正则，问题应该修复了，更新下月连和花连的触发器试一下吧

**Comment by Dream1995** [comment]
> 问题出现原正则在无闪时会错误的将默想层数识别为闪状态，当默想层数为2时判断为月闪存在，触发防打重复闪的叶隐
> 更新了正则，问题应该修复了，更新下月连和花连的触发器试一下吧

好的，十分感谢！
