### ISSUE TITLE
武僧军体拳在没有双龙脚/演武的情况下会卡死

### ISSUE THREAD

**Issue by Anzusull** [Yuee98/FFXIVOneButtonCombo#12]
Hi

首先感谢军体拳一键拯救老年人

##还是和黑魔差不多的问题，一旦同步到低等级，例如50级以下，单体军体拳中会失去两个重要技能而卡死，情况如下：

1.崩拳之后固定是双龙脚，但是等级不够使用会卡住，要手动用连击来代替双龙起手。
2.打完一套如果停在盗龙或猛豹身形时，如果身形断了不会复位军体拳至连击，在没有演武的情况下会直接卡死。

##在AOE的场合，目前主要有两个已发现的问题：

1.震脚状态下固定打3地裂劲，这种情况只能提供阴斗气，我自己的解决方案是再写一个震脚阳斗气连击放在旁边。
2.还是低等级没有演武的情况，和单体一样，会存在不会复位身形，导致无法起手直接卡死的问题。

目前在使用过程中遇到的问题基本就是以上这些，也希望您有时间的时候可以调整一下，非常感谢。
[backup.zip](https://github.com/Yuee98/FFXIVOneButtonCombo/files/8742415/backup.zip)

另：附件zip为我自己写的一些职业的相关触发器，整合程度更大，但是也更死板，同时性能也有待优化，尤其是忍者打起来有时候会把ACT解析跑崩，拿出来主要是希望抛砖引玉。

**Comment by Yuee98** [comment]
Hi, 感谢反馈

1. 一键军体拳确实没有考虑低等级时的状况，不过6.0的更新我也确实是忘了复位这种情况，之后会增加无身形复位，增加后应该可以应付50级以上所有情况，仍然保留的(旧)背/侧身位可以用来50级以下过渡；
2. 武僧AOE循环问题同上，AOE和(旧)背/侧身位用的是同一套模板，等我更新复位后应该可以正常复位；
3. 关于武僧AOE必杀技，我没考虑阳必杀，手动写一个阳必杀很好，我个人的解决方案是偷懒直接手动点破坏和四面；




关于附件，我先大致看了下，之后会详细看看：
1. 忍者忍术，我的建议是自己结印：首先是替换键位，因为忍术cd只有0.5s，而ff14的技能在cd小于0.5s就会进队列，这就导致哪怕ACT解析0延迟，只要连按必定会重复结印，除非强行卡时间不进队列，但这样卡gcd反而会影响输出；然后用ac宏，同样的问题，ac宏不进队列，同时因为延迟的问题恰好500ms是没法保证印可以放出来的，必须留有一定时间的容错，而这样也是会影响输出。归根结底ff14如果想不影响输出必然需要技能进队列，所以我基本上不会写进不了队列的宏（唯一例外是占星自动发卡，强行切目标进队列鲁棒性更低）；
2. 如果忍术一定要缩减键位，那我觉得可以把忍术释放键放到普通连击/AOE连击/任何技能上，这样也可以减少结兔子的情况；
3. 切职业键位初始化是个好点子，我考虑要不要对所有触发器加上一个自动复位（切职业、团灭等等）。




最近我更新的也比较频繁，说一下可能对你有帮助的新连击：
1. 战士、忍者、诗人写了个自动补毒/补buff的基础单体连击，对战士忍者相当于把两套123放在了一起，不是追求极致输出的话可以凑合用；
4. 写了骑士安魂圣灵大宝剑一套，我骑士只有80级测试没啥问题，可以试一下90级是否也正常；
5. 忍者的基础连击增加了90级替换成雷遁；
6. 龙骑同1整合了两套连击到一个键位；
7. 镰刀隐匿挥割基本完善，可以一键变身爆发；

**Comment by Yuee98** [comment]
更新了军体拳连击、AOE连击、旧)背/侧身位的自动复位

**Comment by Yuee98** [comment]
一键军体拳也增加了等级判断，测试在低等级不会卡技能了

**Comment by Anzusull** [comment]
感谢大佬支持

刚刚试了一下军体拳和AOE，目前看起来一切正常，晚上同步低级本再看下，届时反馈。

--------------------------------------------------------------------------------------------
关于忍者结印相关，主要是因为我本人有一定神经方面的基础疾病，在需要精细操作的情况下，会偶发有手抖等问题，最常见的是控制不住的连续收缩手指肌肉造成连点，这也是为什么我在触发器里会采用完全自动的队列结印来规避连续点击这个动作的原因。

我最近在思考的一个情况是调用hotbar copy，配合空宏做防连点，但是因为天地人按键顺序有很多种，需要做很多顺序下的按键映射，工作量比较大还没有做完。

另一个问题是如果采用了上面的方案，忍术打出去之后，会有把原来的hotbar复位回来的问题，如果同时基础连击整合在这条hotbar上，还会面临需要一个空的非共通技能栏来做缓存，将忍术结印之前的hotbar状态复制到该技能栏中，在结印完成之后再复制回来，以此保证基础旋风刃连击不需要从头开始打，当然如果没有这种进阶要求，事先摆好一个复位用的默认键位，直接调用即可，能省很多事。

具体的表现可以参考我之前的附件中镰刀的切换，就是用了hotbar 10做缓存，来保存隐匿挥割之前的连击进度。

**Comment by Yuee98** [comment]
修复了武僧的几个问题：
60级以下虽然没有量谱但是实际上log里有，所以还是会替换必杀；
一键军体拳续buff的时机；
增加了一键军体拳的稳定性；
修复了60级以下没有必杀技时AOE不能在震脚结束后复原的问题。

**Comment by Yuee98** [comment]
加油！我最近也会想想忍者能进队列的忍术的

**Comment by Anzusull** [comment]
> 60级以下虽然没有量谱但是实际上log里有，所以还是会替换必杀

关于这个，如果60级以下的武僧在使用震脚的情况下，因为不会被替换成必杀，所以中间我加了一个大概200ms的缓冲，以免连续点击震脚浪费层数

**Comment by Anzusull** [comment]
悲报

最新版本开演武/震脚的时候AOE固定替换破坏神冲而不是地裂劲，每下亏30威力。

我尝试调整过把AOE里面的震脚条目下command动作调整为30级以上替换地裂劲，30以下替换破坏神冲，但是最终的效果变成了当前开震脚时在哪个体式下，就会打对应体式的AOE连续三下。

**Comment by Yuee98** [comment]
我更换了aoe震脚默认技能，因为有人反馈武僧满级后上位破坏神冲是必爆的，期望威力比地裂劲更高。
在生成触发器的网页，手动把技能9改成地裂劲，可以把震脚默认技能换成相应技能

**Comment by Anzusull** [comment]
理解了，因为我个人原因很少打高难，基本都在低等级随机本徘徊，很少能够用到满级的场景，所以我还是先去替换成地裂劲，之后自己去研究一下如何做等级上的判断好了

**Comment by Anzusull** [comment]
试过了，我犯了个很低级的错误导致了这个状况

> 我尝试调整过把AOE里面的震脚条目下command动作调整为30级以上替换地裂劲，30以下替换破坏神冲，但是最终的效果变成了当前开震脚时在哪个体式下，就会打对应体式的AOE连续三下。

这个问题是我把地**烈**劲写成了地**裂**劲导致的，现在做了按等级判定，按以下规则执行：

1. 震脚为50级技能，能开震脚的时候必定会地烈劲，因此无需判断低等级
2. 开震脚的时候判定，小于82级-地烈劲，大于等于82级-破坏神冲

附件为修改后的判断条件
[震脚 .zip](https://github.com/Yuee98/FFXIVOneButtonCombo/files/8749126/default.zip)

另附上我的震脚打阳斗气的相关连击
[震脚-阳斗气.zip](https://github.com/Yuee98/FFXIVOneButtonCombo/files/8749127/-.zip)

**Comment by Yuee98** [comment]
等级判断容易写，比较懒没开一个新模板，之后考虑写一个自动判断阴阳的aoe循环吧。

刚发现act更新解析后1A行有层数了，后面考虑重构一部分触发器。

**Comment by Yuee98** [comment]
更新了武僧AOE，现在可以根据阴阳斗气自动释放阴阳必杀，同时无必杀/阴必杀时会根据等级判断释放地裂或者破坏。
需要更新武僧-基础和AOE两个触发器。

**Comment by Anzusull** [comment]
网页仓库好像还没有更新，下载下来还是旧的版本

**Comment by Yuee98** [comment]
所有连击都加了复位，切换职业、进本、团灭时会自动复位技能
