### ISSUE TITLE
赤魔长短倒数没法正常切换

### ISSUE THREAD

**Issue by Hillria** [Yuee98/FFXIVOneButtonCombo#14]
测试条件：81级赤魔木桩 雷火连击键位22 风土连击键位23 aoe雷连击键位31 aoe风连击键位32
 
问题描述：赤魔在已经有基础连击的情况下，触发短读条预备的情况下不会自动切换到短读条的对应技能，而是一直停留在长读条，同时有无连续咏唱的时候都是保留在长技能。但同时打完魔三连之后的赤神圣or核爆的情况下又能顺利切换成短读条的对应技能，但读完该短读条技能后又无法切换到长读条的对应技能。aoe连也存在同样的问题，无法正常切换到长读条aoe技能。

附：使用网页生成的对应连击触发器

[new 1.txt](https://github.com/Yuee98/FFXIVOneButtonCombo/files/8790566/new.1.txt)

键位设置如下图
![image](https://user-images.githubusercontent.com/42807105/170811735-630dba06-b814-4bb6-8a20-b883744e8978.png)

测试录制情况如下

1.有连续咏唱无促进
![有连续咏唱无促进](https://user-images.githubusercontent.com/42807105/170812133-e3949eea-1e02-4bfc-8b4b-915d0ccf9696.gif)

2.有连续咏唱有促进
![有连续咏唱有促进](https://user-images.githubusercontent.com/42807105/170812189-e0c7faa2-1f31-4a79-b4b5-264c0a3cd7a4.gif)

3.魔三连
![魔三连](https://user-images.githubusercontent.com/42807105/170812257-22b80dbf-6d4b-483d-969d-87dea10f0073.gif)

4.aoe连情况
![aoe连情况](https://user-images.githubusercontent.com/42807105/170812323-a28cac70-625e-43ef-972c-a2288680c31c.gif)

**Comment by Yuee98** [comment]
发现问题了，是个老问题，获得/失去状态时的正则在抓角色名称的时候没加限位，导致只会抓到角色名称第一个字，巧合的是我id只有一个字所以没测出来bug

现在应该修复了，重新生产触发器再试试吧

p.s. 即刻和促进也会切换长短读条，可以一起测测试试

**Comment by Hillria** [comment]
更新后目前测试一切正常，即刻、促进、连续咏唱均能正常切换长短读条，辛苦debug了
