### ISSUE TITLE
一键连击生成器网页突然无法选择下拉模块

### ISSUE THREAD

**Issue by CAO0028** [Yuee98/FFXIVOneButtonCombo#15]
本来用的挺正常的，突然一键连击生成器的网页没有下拉模块，再也无法正常使用，请问大佬是什么原因？

**Comment by Yuee98** [comment]
可能是网络问题，vercel最近连接不稳定，能访问GitHub的话，可以试试备用地址能不能正常访问，不然的话只能挂代理了。
后续看情况可能会找个国内镜像。

**Comment by CAO0028** [comment]
好，谢谢大佬。我是两个地址都是一样的状况。突然就这样了。

**Comment by Yuee98** [comment]
找到问题了，cdn的问题，jsdelivr国内5月份开始频繁挂，我直接拉到本地了，暂时应该没问题了

**Comment by CAO0028** [comment]
好的！万分感谢大佬！
