### ISSUE TITLE
绝枪aoe连+子弹的优先级问题

### ISSUE THREAD

**Issue by Hillria** [Yuee98/FFXIVOneButtonCombo#18]
昨天日随的时候发现绝枪的aoe连+子弹的连击存在一个小问题，就是在子弹满的情况下，不会优先消耗子弹，而是必须aoe12打完才能切换子弹。
不知道这是逻辑问题还是本身就是这么写的？我觉得应该可以考虑优化一下？
![aoe连情况](https://user-images.githubusercontent.com/42807105/174420309-fb35c917-38b7-45a2-852f-f6ab8326ccb9.gif)

**Comment by Yuee98** [comment]
这个是之前随手当成三连写的，之后会优化成根据子弹判断（最近有点忙，得一段时间后了

**Comment by Yuee98** [comment]
写好了，使用新的“AOE-子弹连”就可以
