### ISSUE TITLE
为什么占星的一键发卡不成功

### ISSUE THREAD

**Issue by yukiasuk** [Yuee98/FFXIVOneButtonCombo#21]
按照大佬的教程试了一遍，在发卡的时候按出来的卡总是会卡住，在聊天框是会出现自动发卡的提示，但是卡发不出去会卡在那

**Comment by Yuee98** [comment]
6.1占星量谱的log line改了，之后调整

**Comment by Yuee98** [comment]
修复了，重新生成触发器试试
