### ISSUE TITLE
镰刀“※绞决-缢杀-隐匿挥割"问题

### ISSUE THREAD

**Issue by HaoyuanZ9859** [Yuee98/FFXIVOneButtonCombo#22]
大佬大佬，刚刚发现镰刀开夜游魂衣后打不出来夜游魂切割和团契了，能麻烦看一下嘛。

**Comment by Yuee98** [comment]
我这里测试是正常的，重新生成下触发器试试呢

**Comment by HaoyuanZ9859** [comment]
今天上线啥也没干就好了，大概是act出现了什么奇怪问题，麻烦大佬了，非常感谢！
