### ISSUE TITLE
实测无法在国际服使用（6.3）

### ISSUE THREAD

**Issue by wdth1** [Yuee98/FFXIVOneButtonCombo#24]
即便更换成对应的英文名也不能触发，不知道大佬有什么头绪

**Comment by Yuee98** [comment]
排查的话可以先试试用触发器里的正则表达式在ACT战斗日志里搜索下，看能不能搜到对应记录。如果能搜到的话，考虑输出的/hotbar set语句是不是出了问题；搜不到的话考虑正则表达式的问题。
我暂时没条件去国际服排查，之后有时间可能会去处理看看。

**Comment by Yuee98** [comment]
根据 #27 可以在国际服使用，查看下名称是否修改正确
