### ISSUE TITLE
机工过热由时长变为层数无法触发热冲击

### ISSUE THREAD

**Issue by Nonovi** [Yuee98/FFXIVOneButtonCombo#26]
作者大大，机工超荷调整后过热由固定时长变为了5层
因为这个改动，现有的触发器无法将超荷替换为热冲击
自己按照dk血乱拜年和战士大风车触发调整了下好像还是不行
能拜托大佬修改下生成器或者教一下应该如何调整触发器的条件判断吗，感谢

**Comment by Yuee98** [comment]
Hello，我最近没有时间玩游戏，不清楚改动如何，过热的层数不知道是多层的buff还是量谱里的数字

如果过热层数还是在量谱里显示，没有单独的buff，可以参考 
https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs
https://goatcorp.github.io/Dalamud/api/Dalamud.Game.ClientState.JobGauge.Types.html


如果过热层数是单独的buff（类似解放之类的），可以参考骑士的【安魂-圣灵-大宝剑】触发器
不过听说骑士6.3也改了，这个触发器可能无法生效，但是思路应该可以参考

**Comment by Yuee98** [comment]
已修复
