### ISSUE TITLE
救命，更新后失效了

### ISSUE THREAD

**Issue by csutangzhiheng** [Yuee98/FFXIVOneButtonCombo#29]
最近更新后上线发现失效了，全部删除重新导入也不行。。。
啊啊啊没有一键连击不会玩游戏啦（狗头

**Comment by Yuee98** [comment]
具体是哪个用不了, 我这里大多数都可以用
或者ACT其他功能可以用吗, 更新下ACT试试?

**Comment by csutangzhiheng** [comment]
额，可能是ACT还在更新吧，我过几天再试试，先A两天
:）

**Comment by csutangzhiheng** [comment]
太棒啦，今天act再次更新后又可以用啦，没有这个我的武士根本按不过来！
