### ISSUE TITLE
关于诗人歌曲循环无法生效

### ISSUE THREAD

**Issue by nightfallhuang** [Yuee98/FFXIVOneButtonCombo#3]
如题，诗人歌曲循环功能无法生效

**Comment by Yuee98** [comment]
你好，我这里测试正常，规则如下：
1. 放浪神时，按键为完美音调；
2. 放浪神结束，按键为贤者歌；
3. 贤者歌期间，按键为军神；
4. 军神期间，按键为放浪神。
1-4构成诗人标准循环

如果按键没有如上述正常循环，可否提供：
1. 其他职业按键循环能否正常使用；
2. 诗人歌曲循环具体怎样无法生效，完全没有反应还是某首歌按键异常。
