### ISSUE TITLE
关于连击中断时间

### ISSUE THREAD

**Issue by Dream1995** [Yuee98/FFXIVOneButtonCombo#5]
现在连击好像都是持续30秒了，是不是可以改成30秒再自动复位

**Comment by Yuee98** [comment]
> 现在连击好像都是持续30秒了，是不是可以改成30秒再自动复位
改成30s了

> 还有舞者的连击好像用不了
这个和1A/1E行的log正则有关, 在一些triggernometry上会有问题, 应该也已经修复了
