### ISSUE TITLE
龙骑的aoe触发条件需要更新

### ISSUE THREAD

**Issue by Ferrothorn** [Yuee98/FFXIVOneButtonCombo#7]
触发条件
^.{14} (AOE)?ActionEffect 1[56]:.{8}:(?<player>[^:]+?):[^:]+:死天枪
应该写作
^.{14} (AOE)?ActionEffect 1[56]:.{8}:(?<player>[^:]+?):[^:]+:(死天枪|龙眼苍穹)
以应对死天枪的升级

**Comment by Yuee98** [comment]
已更新
