### ISSUE TITLE
关于占星一键发卡

### ISSUE THREAD

**Issue by hzyqwq123** [Yuee98/FFXIVOneButtonCombo#9]
大佬您好，请问现在占星一键发卡宏是否有制作，以及是否考虑制作状态判断，如果卡槽有卡则一自动发卡，如果卡槽无卡则抽卡，以此防止60秒循环对齐爆发时出现的问题

**Comment by Yuee98** [comment]
一键发卡做是会打算做，不过我还没开始练占星，要等之后有时间再做了，现在还没排期

**Comment by hzyqwq123** [comment]
辛苦大佬了，最后冒昧问下因为占星宏蛮多的，比如获得小奥秘卡后小奥秘卡替换为出王冠卡，这种宏可以在大佬的即刻复活宏上稍微改一下正则表达来实现吗

**Comment by hzyqwq123** [comment]
谢谢大佬

**Comment by Yuee98** [comment]
单独的 抽卡-重抽 和 发卡-星力 做好了，如果把这俩整合在一起，有个问题是星力要怎么放：
1. 集齐三印就替换为星力，可以保证星力可以第一时间释放出去；
2. 集齐三印且有卡时替换为星力，可以留星力凑三卡到120s爆发；

1更能保证蓝量稳定，2上限更高，我占星不怎么玩，不知道哪一种更符合当前版本占星要求。
当然二者同样的问题是有卡的时候无法监控抽卡cd。

**Comment by SaltFish-X** [comment]
请问6.0的占星自动发卡可以用了吗，能否更新一下教程

**Comment by Yuee98** [comment]
可以用，和之前的用法一样，看之前的教程就可以
https://github.com/Yuee98/FFXIVOneButtonCombo/blob/main/docs/ast_auto_play.md

**Comment by hzyqwq123** [comment]
辛苦大佬了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月21日(星期六) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yuee98/FFXIVOneButtonCombo] 关于占星一键发卡 (Issue #9)





 
单独的 抽卡-重抽 和 发卡-星力 做好了，如果把这俩整合在一起，有个问题是星力要怎么放：
  
集齐三印就替换为星力，可以保证星力可以第一时间释放出去；
 
集齐三印且有卡时替换为星力，可以留星力凑三卡到120s爆发；
  
1更能保证蓝量稳定，2上限更高，我占星不怎么玩，不知道哪一种更符合当前版本占星要求。
 当然二者同样的问题是有卡的时候无法监控抽卡cd。
